### ISSUE TITLE
Aborting apply when creating a stack puts it in a bad state

### ISSUE THREAD

**Issue by patrobinson** [envato/stack_master#187]
After aborting an `apply` command (with Ctrl+C), on an initial stack creation, I got the following error:

```
/usr/local/bundle/gems/stack_master-0.16.0/lib/stack_master/stack.rb:20:in `template_default_parameters': undefined method `fetch' for false:FalseClass (NoMethodError)
```

After deleting the stack this stopped happening.

I suspect this was introduced by https://github.com/envato/stack_master/pull/178/files#diff-cf22d74c8f612a3282d758a02c9d21e7R83, because we may create an empty stack that won't get cleaned up if stack_master is uncleanly terminated. We can optionally:

- Hook the TERM signal and cleanup the stack
- Make StackMaster properly deal with an existing, empty, stack

**Comment by envatopoho** [comment]
+1
Happened when my stack was in `REVIEW_IN_PROGRESS`. Deleting the stack manually sorted it out
At the very least a nicer error message would be useful.

**Comment by samuelsuarezsanchez** [comment]
Stacks are also stuck at `REVIEW_IN_PROGRESS` if user answers _no_ when prompted to apply stack and the user/role stack_master is running under does not have delete stack permission. It might be worth adding a switch to avoid calculating the changeset even if that means we cannot preview the resources that will be affected.

**Comment by patrobinson** [comment]
This was fixed in #202

**Comment by greenu** [comment]
Seeing this in stack_master 1.4.0 when stack is in `REVIEW_IN_PROGRESS` state.

**Comment by patrobinson** [comment]
@greenu can you please open a new issue and describe the steps required to reproduce this error?
